### ISSUE TITLE
Environment configuration issues

### ISSUE THREAD

**Issue by pzhren** [k-han/AutoNovel#2]
Hi,:
I encountered the following error during environment configuration:
$ conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...
CondaIndexError: Invalid index file: https://conda.anaconda.org/usgs-astrogeology/linux-64/repodata.json: Expecting value: line 1 column 1 (char 0)
I guess it's my .condarc file configuration error, but I don't know how to solve it.

**Comment by k-han** [comment]
Hey, there might be something wrong with your conda or system (less likely). FYI, the code was fully tested in CentOS Linux 7 (Core).
