### ISSUE TITLE
about the BCE loss

### ISSUE THREAD

**Issue by liujianzhao6328057** [k-han/AutoNovel#5]
HI, thanks for your great job. Ihave some doubt about the BCE loss. Why  use   prob1_ulb, _= PairEnum(prob2[~mask_lb]) 
            _, prob2_ulb = PairEnum(prob2_bar[~mask_lb])   to decide  if x_i or  x_j is similar or dissimilar instead of directly using  prob1_ulb, prob2_ulb= PairEnum(prob2[~mask_lb]) ?   Thanks very much

**Comment by k-han** [comment]
Hi, this is to make better use of the positive pairs from different transformations of the same sample. If we use `prob1_ulb, prob2_ulb= PairEnum(prob2[~mask_lb])`, there will be pairs formed by a data point and itself. We use `
prob1_ulb, _= PairEnum(prob2[~mask_lb])` and `_, prob2_ulb = PairEnum(prob2_bar[~mask_lb])` to introduce some perturbations on such self-pairs to benefit training, but the effect of this should be very marginal.
