### ISSUE TITLE
about the similarity prediction

### ISSUE THREAD

**Issue by liujianzhao6328057** [k-han/AutoNovel#6]
Hi,  have you tried to use the dot product of two normalized representation vectors z_i and z_j to compute the similarity instead of the softmax output ?

**Comment by k-han** [comment]
We have experimented with the dot product. It tends to be more sensitive to the choice of different thresholds. You might need to tweak the thresholds on different datasets. But with a proper threshold, you may also obtain reasonably good results by replacing the ranking statistics with the dot product in our framework.
